version: '3.8'

services:
  endee:
    image: endeeio/endee-server:latest
    container_name: endee-server
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    ports:
      - "8080:8080"
    volumes:
      - ./endee-data:/data
    restart: unless-stopped
    environment:
      # NDD_AUTH_TOKEN is disabled in this example for ease of use, but can be configured
      - NDD_AUTH_TOKEN=
      - NDD_NUM_THREADS=0
